config/routes.rb
Rails.application.routes.draw do
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home 
  get 'sessions/signup' => 'sessions#signup', as: :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root 'sessions#new'
  get 'login' => 'sessions#new', as: :loginpage
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  resources :searches
  resources :books do 
    resources :posts
  end
  resources :users 

  
  resources :comments, only: [:new, :create, :show]

  match ':controller(/:action(/:id))', :via => :get
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :books
  has_many :book_histories
  has_many :posts, through: :books 
  has_many :comments, through: :posts
  has_many :related_books, class_name: 'books'
  before_save { self.email = email.downcase }
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, length: { minimum: 8 }, presence: true
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def index 
    @users = User.all
  end 

  def new
    @user = User.new
  end 

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User created successfully' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end 
  end 

  def show
  end 

  def edit
  end 

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Profile successfully Updated' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end 
  end 

  def destroy
    user_books = Book.find_by(user_id: @user.id)
    if user_books == nil
      @user.destroy
      flash[:notice] = 'User was successfully deleted'
      redirect_to users_url
    else
      flash[:danger] = 'Checked out! cannot delete'
      redirect_to users_url
    end
  end 

  private

  def find_user
    @user = User.find(params[:id])
  end 

  def user_params
    params.require(:user).permit(:name, :email, :password, :address, :phone, :is_admin, :is_deleted)
  end 

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class=" input-group">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :is_admin, "Admin?" %><br>
    <%= f.check_box :is_admin %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_form_edit.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control", placeholder: "password" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control", placeholder: "Address" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "phone number" %>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', :class => "btn btn-success" %>
  </div>
<% end %>

app/views/users/_form_password.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% if @current_user.is_admin? %>
<h1>Edit Profile</h1>

<%= render 'form_edit' %>
<%else%>
<blockquote>
  <p class="text-danger">You are not authorized to view this page!</p>
</blockquote>
<% end %>

app/views/users/edit_password.html.erb
<h1>Editing User</h1>

<%= render 'form_password' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% if @current_user.is_admin? %>
<p id="notice"><%= notice %></p>

<h1>User List</h1>

<table class="table table-hover table-responsive">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.address %></td>
        <td><%= user.phone %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Show', user, class: "btn btn-success", :style => "color: #ffffff"%></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" , :style => "color: #ffffff"%></td>
        <td><%= link_to 'View Checkout History', check_user_history_path(:data => {:user_id => user.id, :book_id => nil}), :class => "btn btn-success", :style => "color: #ffffff"%></td>
        <%if user.id != @current_user.id && !user.super_admin %>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" , :style => "color: #ffffff"%></td>

        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'Add New User', new_user_path, class: "btn btn-primary", style: "color: #ffffff" %>
<%else%>
<blockquote>
  <p class="text-danger">You are not authorized to view this page!</p>
</blockquote>
<% end %>

app/views/users/new.html.erb
<% if @current_user.is_admin? %>

    <h1>New User</h1>

    <%= render 'form' %>
<%else%>
    <blockquote>
      <p class="text-danger">You are not authorized to view this page!</p>
    </blockquote>
<%end%>

app/views/users/show.html.erb
<%if (@user.id == @current_user.id) || @current_user.is_admin %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>
<br/><br>
<%= link_to 'Back', users_path, :class => "btn btn-warning", :style => "color: #ffffff" %>
<%else%>
<blockquote>
  <p class="text-danger">You are not authorized to view this page!</p>
</blockquote>
<% end %>