config/routes.rb
Rails.application.routes.draw do
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home 
  get 'sessions/signup' => 'sessions#signup', as: :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root 'sessions#new'
  get 'login' => 'sessions#new', as: :loginpage
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  resources :searches
  resources :books do 
    resources :posts
  end
  resources :users 

  
  resources :comments, only: [:new, :create, :show]

  match ':controller(/:action(/:id))', :via => :get
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :user
  has_many :book_histories
  has_many :posts
  has_many :comments, through: :posts
  validates :title, presence: true
  validates :isbn, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :edit, :destroy, :update]

  def index
    @books = Book.all.order('created_at DESC')
  end 

  def new
    @book = Book.new
  end 

  def create
    @book = Book.new(book_params)
    @book.is_deleted = false
    if @book.save
      redirect_to @book, notice: 'Book was successfully added!'
    else
      render 'new'
    end 
  end 

  def show
  end 

  def edit
  end 

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated!'
    else
      render :edit, notice: 'Error is updating, try again!'
    end 
  end 

  def destroy
    if @book.present?
      @book.is_deleted = true
      @book.save
      redirect_to books_path, notice: 'Book was successfully destroyed!'
    else
      render :new, notice: 'Error in deleting, try again!'
    end
  end 

  def borrow
    @book = Book.find(params[:id])
    @book.is_borrowed = true
    @book.user_id = session[:user_id]

    if @book.save
      redirect_to @book, notice: 'Book is borrowed'
    else
      render 'new'
    end 

    #Create check out history of book
    create_book_history(params[:id], session[:user_id], Time.zone.now)
  end

  def create_book_history(book_id, user_id, check_out_date)
    @book_history = BookHistory.new
    @book_history.book_id = book_id
    @book_history.user_id = user_id
    @book_history.check_out_date = check_out_date
    @book_history.save!
  end 

  def return
    @book = Book.find(params[:id])
    invalid_return = false
    if @book.is_borrowed && (@book.user_id != @current_user.id)
      invalid_return = false
    end 
    send_mail = false
    if @book.is_requested
      user = User.find(@book.requested_by)
      send_mail = true
    end 

    @book.is_borrowed = false
    @book.user_id = nil
    @book.requested_by = nil
    @book.is_requested = false

    if !invalid_return and @book.save!
      redirect_to @book, notice: 'Booking was successfully borrowed!'
    else
      render 'show', notice: 'Invalid Action'
    end

    if send_mail
      send_email_to_requester(user, @book.title)
    end 

    complete_book_history(params[:id], session[:user_id], Time.zone.now)
  end

  def send_email_to_requester(user, bookname)
    Notifier.send_notification(user.email, user.name, book_name).deliver_now!
  end

  def complete_book_history(book_id, user_id, check_in_date)
    @book_history = BookHistory.find_by(book_id: book_id, user_id: user_id, check_in_date: nil)
    @book_history.check_in_date = check_in_date
    @book_history.save
  end

  def request_book
    @book = Book.find(params[:id])
    @book.is_requested = true 
    @book.requested_by = session[:user_id]
    if @book.save!
      render :show, status: :ok, location: @book 
    else
      render :show
    end 
  end 

  def cancel_request
    @book = Book.find(params[:id])
    @book.is_requested = false
    @book.requested_by = nil 
    if @book.save
      render :show, status: :ok, location: @book 
    else
      render :show
    end
  end

  def calc_fine
    @book = Book.find(params[:id])
    @fine = 0
    no_of_days = (@book.check_in_date.strftime("%Y-%m-%d") - @book.check_out_date.strftime("%Y-%m-%d"))
    if (@book.is_requested and no_of_days > 15.days) 
      @fine += (no_of_days)*0.05
    end 
  end 

  private

  def find_book
    @book = Book.find(params[:id])
  end 

  def book_params
    params.require(:book).permit(:title, :description, :author, :isbn, :is_borrowed, :is_deleted)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<div class="container">
  <%= form_for(@book) do |f| %>
    <div class="field">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_field :description, class: 'form-control'%>
    </div>
    <div class="field">
      <%= f.label :author %><br>
      <%= f.text_field :author, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :isbn %><br>
      <%= f.text_field :isbn, class: 'form-control' %>
    </div><br>

    <div class="actions">
      <%= f.submit :class => "btn btn-success", :style => "color: #ffffff" %>
    </div><br>
  <% end %>
</div>

app/views/books/_form_edit.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-success", :style => "color: #ffffff" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<% if @current_user.is_admin %>
<h1>Editing Book</h1>

<%= render 'form_edit' %>

<%= link_to 'Back', books_path, :class => "btn btn-primary", :style => "color: #ffffff" %>
<%else%>
<blockquote>
	<p class="text-danger">You are not authorized to view this page!</p>
</blockquote>
<% end %>

app/views/books/index.html.erb
<%if @current_user.is_admin %>
  <%= link_to 'Add Book', new_book_path, :class => "btn btn-success", :style => "color: #ffffff; position: absolute; left: 10%;" %>
<% end %>
<p class="lead" style="text-align: center">All Books</p><hr>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Isbn</th>
      <th>Status</th>
      <% if @current_user.is_admin %>
      <th>Checked out by</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @books.each do |book| %>
      <tbody>
        <tr>
          <td><%= book.title %></td>
          <td><%= book.description %></td>
          <td><%= book.author %></td>
          <td><%= book.isbn %></td>
          <% if book.is_borrowed %>
            <td><span class="label label-danger">Checked out</span></td>
          <% else %>
            <td><span class="label label-success">Available</span></td>
          <%end%>
          <% if book.is_borrowed && @current_user.is_admin %>
            <% @user = User.find(book.user_id)%>
            <td><%=@user.name%> (<%=@user.email %>)</td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= link_to 'Show', book, :class => "btn btn-primary", :style => "color: #ffffff" %></td>
          <%if @current_user.is_admin? %>
              <td><%= link_to 'View Checkout History', check_user_history_path(:data => {:user_id => nil, :book_id => book.id}), :class => "btn btn-success", :style => "color: #ffffff"%></td>
          <td><%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning", :style => "color: #ffffff" %></td>
          <% if !book.is_borrowed %>
          <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color: #ffffff" %></td>
          <% else %><td></td>
          <% end %>
          <% end %>
          <%if book.is_borrowed %>

          <% if book.user_id == @current_user.id %>

          <td><%= link_to 'Return', return_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
          <%else%>
          <% if !book.is_requested %>
          <td><%= link_to 'Request Notification', request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
          <%else%>
          <% if book.is_requested && (book.requested_by == @current_user.id) %>          
          <td><%= link_to 'Cancel Notification', cancel_request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
          <%end%>
          <%end%>
          <%end%>
          <%else%>
          <td><%=link_to 'Check out', borrow_book_path(:id => book.id), :class => "btn btn-success", :style => "color: #ffffff"%></td>
          <% end %>
          <% end %>
        </tr>
      </tbody>
    </table>

app/views/books/new.html.erb
<h1 style="text-align: center">New Book</h1>
<%= render 'form' %>
<%= link_to 'Back', books_path, class: 'btn btn-info', style: 'position: absolute; left: 6.2%; color: #ffffff' %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table">
  <thead>
    <tr>
      <th><strong>Title</strong></th>
      <th><strong>Description</strong></th>
      <th><strong>Author</strong></th>
      <th><strong>Isbn</strong></th>
      <th><strong>Status</strong></th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td><%= @book.title %></td>
      <td><%= @book.description %></td>
      <td><%= @book.author %></td>
      <td><%= @book.isbn %></td>
      <% if @book.is_borrowed %>
      <td><span class="label label-danger">Checked out</span></td>
      <%else%>
      <td><span class="label label-success">Available</span></td>
      <%end%>
    </tr>
  </tbody>
</table>

<%if @current_user.is_admin %>
<%= link_to 'Edit', edit_book_path(@book), :class => "btn btn-danger", :style => "color: #ffffff" %> | 
<% end %>
<%= link_to 'Back', books_path, :class => "btn btn-warning", :style => "position: relative; left: 48%; color: #ffffff" %><br><br>
<%= render 'posts/form' %><br>

<!-- Show all the reviews and comments of the post -->
<% @book.posts.each do |post| %>
    <div class="form-field">
      Title: <%= post.title %><br>
    </div>
    <div class="form-field">
      Content: <%= post.description %><br>
    </div><br><hr>
  <% end %>