config/routes.rb
Rails.application.routes.draw do
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home 
  get 'sessions/signup' => 'sessions#signup', as: :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root 'sessions#new'
  get 'login' => 'sessions#new', as: :loginpage
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  resources :searches
  resources :books do 
    resources :posts
  end
  resources :users 

  
  resources :comments, only: [:new, :create, :show]

  match ':controller(/:action(/:id))', :via => :get
end

app/models/search.rb
class Search < ActiveRecord::Base

  def search_books
    books = Book.all 
    books = books.where("isbn LIKE ? and title LIKE ? and description LIKE ? and author LIKE ?
                        and is_deleted = ?", "%#{isbn}","%#{title}", "%#{description}", "%#{author}", false)
    return books
  end
  
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def new
    @search = Search.new
  end 

  def create
    @search = Search.create(search_params)
    redirect_to @search 
  end 

  def show
    @search = Search.find(params[:id])
  end 

  private

  def search_params
    params.require(:search).permit(:isbn, :title, :description, :author)
  end 

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/new.html.erb
<%= form_for @search, html: { class: "pure-form" } do |s| %>
  <div class="field">
    <%= s.label :isbn %><br>
    <%= s.text_field :isbn %>
  </div>
  <div class="field">
    <%= s.label :title %><br>
    <%= s.text_field :title %>
  </div>
  <div class="field">
    <%= s.label :author %><br>
    <%= s.text_field :author %>
  </div><br>
  <div class="actions">
    <%= s.submit "Search", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<% if @search.search_books.empty? %>
<blockquote>
<p class="lead">No Books Found!</p>
</blockquote>
<% else %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Isbn</th>
      <th>Status</th>
      <%if @current_user.is_admin %>
      <th>Checked out by </th>
      <%end%>
      <th colspan="3"></th>
    </tr>
  </thead>
  <% @search.search_books.each do |book| %>

	<tbody>
	    <tr>
	      <td><%= book.title %></td>
	      <td><%= book.description %></td>
	      <td><%= book.author %></td>
	      <td><%= book.isbn %></td>
	      <% if book.is_borrowed %>
	      	<td><span class="label label-danger">Checked out</span></td>
	      <% else %>
	      	<td><span class="label label-success">Available</span></td>
	      <%end%>
	      <% if book.is_borrowed && @current_user.is_admin %>
	      	<% @user = User.find(book.user_id) %>
	      <td><%=@user.name%> (<%=@user.email %>)</td>
	      <% else %>
	      	<td></td>
	      <%end%>
	      <td><%= link_to 'Show', book, :class => "btn btn-primary", :style => "color: #ffffff" %></td>
	      <% if @current_user.is_admin? %>
	      	<td><%= link_to 'Edit', edit_book_path(book), :class => "btn btn-warning", :style => "color: #ffffff" %></td>
	      <%if !book.is_borrowed %>
	  		<td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger", :style => "color: #ffffff" %></td>
	      <% else %><td></td>
	      <% end %>
	      <% end %>
	      <% if book.is_borrowed %>
	      <% if book.user_id == @current_user.id %>
	      <td><%= link_to 'Return', return_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
	      <%else%>
	      <% if !book.is_requested %>
	      <td><%= link_to 'Request Notification', request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
	      <% else %>
	      <% if book.is_requested && (book.requested_by == @current_user.id) %>          
	      <td><%= link_to 'Cancel Notification', cancel_request_book_path(:id => book.id), :class => "btn btn-warning", :style => "color: #ffffff"%></td>
	      <% end %>
	      <% end %>
	      <% end %>
	      <% else %>
	      <td><%=link_to 'Check out', borrow_book_path(:id => book.id), :class => "btn btn-success", :style => "color: #ffffff"%></td>
	      <% end %>
	      <% end %>
	    </tr>
	</tbody>
</table>
<br/>
<% end %>
<%= link_to "Back", new_search_path, :class => "btn btn-warning", :style => "color: #fff" %>