config/routes.rb
Rails.application.routes.draw do
  resources :book_histories
  get 'homes/new'
  get 'homes/show' => 'homes#show', as: :home 
  get 'sessions/signup' => 'sessions#signup', as: :signup
  post 'sessions/new_user' => 'sessions#new_user'
  root 'sessions#new'
  get 'login' => 'sessions#new', as: :loginpage
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'books/:id/borrow' => 'books#borrow', :as => :borrow_book
  get 'book_histories/:data/index' => 'book_histories#index', :as =>:check_user_history
  get 'books/:id/request' => 'books#request_book', :as => :request_book
  get 'books/:id/return' => 'books#return', :as => :return_book
  get 'books/:id/cancel_request' => 'books#cancel_request', :as => :cancel_request_book

  resources :searches
  resources :books do 
    resources :posts
  end
  resources :users 

  
  resources :comments, only: [:new, :create, :show]

  match ':controller(/:action(/:id))', :via => :get
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse" style="background-color: #00deff">
    <div class="container">
      <nav>
        <% if logged_in? %>
          <ul class="nav navbar-nav navbar-left">
            <div style="margin: 8px 0px 0px 0px; float: left">
              <%= link_to "Home", home_path, class: 'btn btn-info', style: 'color: black' %>
            </div>
            <div style="margin: 15px 0px 0px 20px; float: left">
              <li style="color: black; font-size: 14px">Welcome, <%= @current_user.name %>!</li>
            </div>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="color: #ffffff">
                <b class="caret" style="border-top:9px solid #ffffff"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "View Profile", user_path(@current_user.id) %></li>
                <li><%= link_to "Edit Profile", edit_user_path(@current_user.id) %></li>
                <li class="divider"></li>
                <li><%= link_to '<i class="glyphicon glyphicon-off"></i> Log out'.html_safe, logout_path, method: :delete, :style => "float: left" %></li>
              </ul>
            </li>
          </ul>
        <% end %>
      </nav>
    </div>
  </header>

  <br><br><br>
    <%= yield %>

</body>
</html>